language: python
python:
  - "3.7"
install:
  - 'cp contrib/env-sample .env'
  - 'pip install coveralls'
  - 'pip install pipenv'
  - 'pipenv sync'
script:
  - python manage.py test
  - coverage run --source=communicare manage.py test
after_success:
  - coveralls