# Generated by Django 2.1.4 on 2019-01-09 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='nome')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='nome completo')),
                ('phone', models.CharField(max_length=20, verbose_name='telefone')),
                ('cpf', models.CharField(max_length=14, verbose_name='CPF')),
                ('rg', models.CharField(max_length=20, verbose_name='RG')),
                ('address', models.CharField(max_length=255, verbose_name='endereço completo')),
                ('cep', models.CharField(max_length=10, verbose_name='CEP')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('profession', models.CharField(blank=True, max_length=255, null=True, verbose_name='profissão')),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='idade')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.City')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='título')),
                ('subtitle', models.CharField(max_length=255, verbose_name='subtítulo')),
                ('start_date', models.DateTimeField(verbose_name='data de início')),
                ('end_date', models.DateTimeField(verbose_name='data de término')),
                ('details', models.TextField(verbose_name='detalhes')),
            ],
        ),
        migrations.CreateModel(
            name='FederativeUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initials', models.CharField(max_length=2, verbose_name='sigla')),
                ('name', models.CharField(max_length=255, verbose_name='nome')),
            ],
        ),
        migrations.CreateModel(
            name='Places',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='título')),
                ('address', models.CharField(max_length=255, verbose_name='endereço')),
                ('link_to_map', models.URLField(verbose_name='link para o mapa')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.City')),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='descrição')),
                ('position', models.SmallIntegerField(default=0, help_text='99 para "Outros"', verbose_name='posição')),
            ],
            options={
                'ordering': ('position', 'description'),
            },
        ),
        migrations.AddField(
            model_name='event',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Places'),
        ),
        migrations.AddField(
            model_name='event',
            name='registrations',
            field=models.ManyToManyField(to='core.Customer'),
        ),
        migrations.AddField(
            model_name='customer',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Source'),
        ),
        migrations.AddField(
            model_name='city',
            name='uf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.FederativeUnit'),
        ),
    ]
