# Generated by Django 2.1.4 on 2019-01-11 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190109_1646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='city',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='source',
        ),
        migrations.RemoveField(
            model_name='event',
            name='place',
        ),
        migrations.RemoveField(
            model_name='event',
            name='registrations',
        ),
        migrations.RemoveField(
            model_name='places',
            name='city',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='Places',
        ),
    ]
