# Generated by Django 2.1.4 on 2019-01-11 21:29

import communicare.core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190111_1928'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='nome completo')),
                ('phone', models.CharField(max_length=20, verbose_name='telefone')),
                ('cpf', models.CharField(max_length=14, verbose_name='CPF')),
                ('rg', models.CharField(max_length=20, verbose_name='RG')),
                ('address', models.CharField(max_length=255, verbose_name='endereço completo')),
                ('cep', models.CharField(max_length=10, verbose_name='CEP')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('profession', models.CharField(blank=True, max_length=255, null=True, verbose_name='profissão')),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='idade')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.City')),
                ('source', models.ForeignKey(default=communicare.core.models.get_default_source, on_delete=django.db.models.deletion.PROTECT, to='core.Source')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='título')),
                ('subtitle', models.CharField(max_length=255, verbose_name='subtítulo')),
                ('start_date', models.DateTimeField(verbose_name='data de início')),
                ('end_date', models.DateTimeField(verbose_name='data de término')),
                ('details', models.TextField(verbose_name='detalhes')),
            ],
            options={
                'verbose_name': 'evento',
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='título')),
                ('address', models.CharField(max_length=255, verbose_name='endereço')),
                ('link_to_map', models.URLField(verbose_name='link para o mapa')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.City')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Place'),
        ),
        migrations.AddField(
            model_name='event',
            name='registrations',
            field=models.ManyToManyField(to='core.Customer'),
        ),
    ]
