# Generated by Django 2.1.4 on 2019-01-12 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190111_1929'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'cidade'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'cliente'},
        ),
        migrations.AlterModelOptions(
            name='place',
            options={'verbose_name': 'local', 'verbose_name_plural': 'locais'},
        ),
        migrations.AlterModelOptions(
            name='source',
            options={'ordering': ('position', 'description'), 'verbose_name': 'indicação', 'verbose_name_plural': 'indicações'},
        ),
        migrations.AddField(
            model_name='event',
            name='open_for_subscriptions',
            field=models.BooleanField(default=False, verbose_name='aberto para inscrições'),
        ),
        migrations.AlterField(
            model_name='event',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Place', verbose_name='local'),
        ),
        migrations.AlterField(
            model_name='event',
            name='registrations',
            field=models.ManyToManyField(blank=True, to='core.Customer', verbose_name='clientes'),
        ),
        migrations.AlterField(
            model_name='place',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.City', verbose_name='cidade'),
        ),
    ]
