# Generated by Django 2.1.4 on 2019-01-18 14:48

import communicare.core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190112_1231'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='federativeunit',
            options={'verbose_name': 'unidade federativa'},
        ),
        migrations.AddField(
            model_name='event',
            name='slug',
            field=models.SlugField(default='invalid', help_text='Preenchido automaticamente, não editar.', max_length=255, unique=True, verbose_name='Slug / URL'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.City', verbose_name='cidade'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='e-mail'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='source',
            field=models.ForeignKey(default=communicare.core.models.get_default_source, on_delete=django.db.models.deletion.PROTECT, to='core.Source', verbose_name='como nos conheceu'),
        ),
        migrations.AlterField(
            model_name='event',
            name='subtitle',
            field=models.CharField(max_length=120, verbose_name='subtítulo'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=135, verbose_name='título'),
        ),
    ]
