# Generated by Django 2.1.5 on 2019-01-25 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20190118_1817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='registrations',
        ),
    ]
