# Generated by Django 2.1.5 on 2019-01-25 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_event_registrations'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_sent', models.BooleanField(default=False, verbose_name='contrato enviado?')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Customer')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Event')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='registrations',
            field=models.ManyToManyField(blank=True, through='core.Registration', to='core.Customer', verbose_name='clientes'),
        ),
    ]
