# Generated by Django 2.1.5 on 2019-02-02 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20190125_1208'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ('name',), 'verbose_name': 'cliente'},
        ),
        migrations.AlterModelOptions(
            name='registration',
            options={'verbose_name': 'inscrição', 'verbose_name_plural': 'inscrições'},
        ),
        migrations.AlterField(
            model_name='registration',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Customer', verbose_name='cliente'),
        ),
    ]
