# Generated by Django 2.1.5 on 2019-02-02 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20190202_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='image',
            field=models.ImageField(null=True, upload_to='images/place/', verbose_name='imagem'),
        ),
    ]
