# Generated by Django 2.1.5 on 2019-02-05 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_testimony'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimony',
            name='visible',
            field=models.BooleanField(default=True, verbose_name='visível'),
        ),
    ]
