# Generated by Django 2.1.5 on 2019-02-06 14:31

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_testimony_visible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimony',
            name='image',
            field=cloudinary.models.CloudinaryField(help_text='Imagem quadrada com no mínimo 170px', max_length=255, verbose_name='imagem'),
        ),
    ]
