# Generated by Django 2.1.5 on 2019-02-06 14:36

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20190206_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='imagem'),
        ),
    ]
