# Generated by Django 2.1.5 on 2019-02-07 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20190206_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('tre_ora', 'Treinamento de Oratória'), ('cur_hip', 'Curso de Hipnose na Prática'), ('tre_iem', 'Treinamento de Inteligência Emocional')], default='tre_ora', max_length=7, verbose_name='tipo'),
            preserve_default=False,
        ),
    ]
