# Generated by Django 2.1.5 on 2019-02-07 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='valor'),
            preserve_default=False,
        ),
    ]
