# Generated by Django 2.1.5 on 2019-02-11 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_event_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='federativeunit',
            name='initials',
            field=models.CharField(max_length=2, unique=True, verbose_name='sigla'),
        ),
        migrations.AlterUniqueTogether(
            name='city',
            unique_together={('uf', 'name')},
        ),
    ]
