# Generated by Django 2.1.7 on 2019-02-12 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20190211_1306'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ('name',), 'verbose_name': 'cidade'},
        ),
    ]
