# Generated by Django 2.1.7 on 2019-03-04 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20190215_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='financial_generated',
            field=models.BooleanField(default=False, verbose_name='financeiro gerado?'),
        ),
        migrations.AddField(
            model_name='registration',
            name='financial_observations',
            field=models.TextField(null=True, verbose_name='observações financeiras'),
        ),
    ]
