# Generated by Django 2.1.7 on 2019-03-13 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20190313_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='nf_status',
            field=models.CharField(blank=True, choices=[('', ''), ('P', 'Pendente'), ('E', 'Emitida')], default='P', max_length=1, verbose_name='Situação NF'),
        ),
    ]
