# Generated by Django 2.1.8 on 2019-08-05 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_auto_20190805_1621'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaitingList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('tre_ora', 'Treinamento de Oratória'), ('cur_hip', 'Curso de Hipnose Clínica'), ('tre_iem', 'Treinamento de Inteligência Emocional')], max_length=7, verbose_name='tipo')),
                ('slug', models.SlugField(help_text='Preenchido automaticamente, não editar.', max_length=255, unique=True, verbose_name='Slug / URL')),
            ],
            options={
                'verbose_name': 'lista de espera',
                'verbose_name_plural': 'listas de espera',
            },
        ),
        migrations.CreateModel(
            name='Waitlisted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='nome completo')),
                ('phone', models.CharField(max_length=20, verbose_name='telefone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='e-mail')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.City', verbose_name='cidade')),
                ('waiting_list', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.WaitingList')),
            ],
            options={
                'verbose_name': 'interessado',
            },
        ),
    ]
