# Generated by Django 2.1.8 on 2019-09-02 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_waitinglist_waitlisted'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='amount_lote1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='valor lote 1'),
        ),
        migrations.AddField(
            model_name='event',
            name='amount_lote2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='valor lote 2'),
        ),
        migrations.AddField(
            model_name='event',
            name='amount_lote3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='valor lote 3'),
        ),
        migrations.AddField(
            model_name='event',
            name='end_date_lote1',
            field=models.DateTimeField(blank=True, null=True, verbose_name='data de término lote 1'),
        ),
        migrations.AddField(
            model_name='event',
            name='end_date_lote2',
            field=models.DateTimeField(blank=True, null=True, verbose_name='data de término lote 2'),
        ),
        migrations.AddField(
            model_name='event',
            name='end_date_lote3',
            field=models.DateTimeField(blank=True, null=True, verbose_name='data de término lote 3'),
        ),
        migrations.AddField(
            model_name='event',
            name='start_date_lote1',
            field=models.DateTimeField(blank=True, null=True, verbose_name='data de início lote 1'),
        ),
        migrations.AddField(
            model_name='event',
            name='start_date_lote2',
            field=models.DateTimeField(blank=True, null=True, verbose_name='data de início lote 2'),
        ),
        migrations.AddField(
            model_name='event',
            name='start_date_lote3',
            field=models.DateTimeField(blank=True, null=True, verbose_name='data de início lote 3'),
        ),
        migrations.AlterField(
            model_name='event',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='valor'),
        ),
    ]
