# Generated by Django 2.1.8 on 2019-09-11 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_auto_20190902_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='net_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='valor líquido'),
        ),
    ]
