# Generated by Django 2.1.8 on 2019-09-25 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_lead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='e-mail'),
        ),
    ]
