# Generated by Django 2.1.8 on 2019-10-03 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_lecture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='financial_generated',
            field=models.BooleanField(default=False, verbose_name='recebimento confirmado?'),
        ),
    ]
