# Generated by Django 2.1.8 on 2019-11-04 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_auto_20191104_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='audience', to='core.Lead', verbose_name='participantes'),
        ),
    ]
