# Generated by Django 2.1.8 on 2019-11-04 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_auto_20191104_0924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='city',
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='participants',
        ),
        migrations.DeleteModel(
            name='Lecture',
        ),
    ]
