# Generated by Django 2.1.8 on 2019-11-04 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_auto_20191104_0932'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='audience',
            options={'verbose_name': 'plateia', 'verbose_name_plural': 'plateia'},
        ),
    ]
