# Generated by Django 2.1.8 on 2020-03-02 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_auto_20191104_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='external_subscriptions',
            field=models.URLField(blank=True, null=True, verbose_name='inscrição externa'),
        ),
    ]
