# Generated by Django 2.1.8 on 2020-04-13 14:00

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_gallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=cloudinary.models.CloudinaryField(help_text='Manter um padrão e ter no máximo 1000px', max_length=255, verbose_name='imagem'),
        ),
    ]
