# Generated by Django 2.1.8 on 2020-04-13 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_testimonyhipnoterapia'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestimonyHipnoterapia',
        ),
    ]
