# Generated by Django 3.1.1 on 2021-02-05 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_testimonyhipnoterapia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='telefone'),
        ),
    ]
